CREATE TABLE "traffic_deaths" (
	"id" serial PRIMARY KEY NOT NULL,
	"contador" integer,
	"tipobito" varchar(1),
	"dtobito" date NOT NULL,
	"horaobito" text,
	"natural" varchar(3),
	"codmunnatu" integer,
	"dtnasc" date,
	"idade" integer,
	"sexo" varchar(1),
	"racacor" varchar(1),
	"estciv" varchar(1),
	"esc2010" varchar(1),
	"seriescfal" varchar(2),
	"ocup" varchar(6),
	"codmunres" integer,
	"lococor" varchar(1),
	"codmunocor" integer,
	"linhaa" text,
	"linhab" text,
	"linhac" text,
	"linhad" text,
	"linhaii" text,
	"circobito" varchar(1),
	"acidtrab" varchar(1),
	"fonte" varchar(1),
	"origem" varchar(1),
	"esc" varchar(1),
	"exame" varchar(1),
	"cirurgia" varchar(1),
	"dtinvestig" date,
	"causabas_o" text,
	"causabas" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "check_sexo" CHECK ("traffic_deaths"."sexo" IN ('0', '1', '2') OR "traffic_deaths"."sexo" IS NULL),
	CONSTRAINT "check_tipobito" CHECK ("traffic_deaths"."tipobito" IN ('1', '2') OR "traffic_deaths"."tipobito" IS NULL),
	CONSTRAINT "check_acidtrab" CHECK ("traffic_deaths"."acidtrab" IN ('1', '2', '9') OR "traffic_deaths"."acidtrab" IS NULL)
);
