CREATE TABLE "bicycle_racks" (
	"id" serial PRIMARY KEY NOT NULL,
	"osm_id" text,
	"osm_type" text,
	"coordinates" text,
	"name" text,
	"description" text,
	"amenity" text DEFAULT 'bicycle_parking',
	"bicycle_parking" text,
	"capacity" text,
	"access" text,
	"covered" text,
	"fee" text,
	"supervised" text,
	"lit" text,
	"operator" text,
	"operator_type" text,
	"building" text,
	"level" text,
	"surface" text,
	"addr_city" text,
	"addr_street" text,
	"addr_housenumber" text,
	"addr_suburb" text,
	"addr_postcode" text,
	"opening_hours" text,
	"payment_none" text,
	"ref" text,
	"source" text,
	"source_date" text,
	"wikidata" text,
	"wikipedia" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "bicycle_racks_osm_id_unique" UNIQUE("osm_id")
);
