CREATE TABLE "emergency_calls" (
	"id" serial PRIMARY KEY NOT NULL,
	"original_id" integer NOT NULL,
	"date" timestamp NOT NULL,
	"time_minute" text NOT NULL,
	"municipality" text,
	"neighborhood" text,
	"address" text,
	"call_origin" text,
	"origin_type" text,
	"subtype" text,
	"gender" text,
	"age" integer,
	"finalization_reason" text,
	"outcome_reason" text,
	"type" text,
	"category" text,
	"finalization_reason_normalized" text,
	"outcome_reason_normalized" text,
	"finalization_category" text,
	"outcome_category" text,
	"pcr_address" text,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
