CREATE TABLE "bicycle_racks" (
	"id" serial PRIMARY KEY NOT NULL,
	"osm_id" text,
	"osm_type" text,
	"name" text,
	"description" text,
	"amenity" text DEFAULT 'bicycle_parking',
	"bicycle_parking" text,
	"capacity" text,
	"access" text,
	"covered" text,
	"fee" text,
	"supervised" text,
	"lit" text,
	"operator" text,
	"operator_type" text,
	"ref" text,
	"level" text,
	"surface" text,
	"building" text,
	"payment_none" text,
	"source" text,
	"source_date" text,
	"metadata" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
